### PR TITLE
#130 - add packages and restructure

### LINKED ISSUE #130: Add packages and restructure classes
I'd suggest restructure packages and rename some classes. The main idea is to introduce `asto` package and put all classes dependent from storage into this package and introduce `proxy` package for proxy-related classes. Interfaces should be placed into "root" package:
```
|-- com.artipie.maven/
  -- asto/
     |-- AstoMaven.java
     |-- RepositoryChecksums.java
     |-- AstoRp.java (renamed from RpLocal.java)
     |-- StorageCache.java
     |-- AstoUpload.java (implements ValidUpload.java, currently inner class of ValidUpload.java)
  -- proxy/
     |-- RpRemote.java
  -- metadata/
     |-- MavenMetadata.java
     |-- ArtifactsMetadata.java
  |-- ProxyCache.java
  |-- Repository.java
  |-- ValidUpload.java
  |-- Maven.java
```
`http` stays as is.

### PR DESCRIPTION
**Pull request by olenagerasimova**
Closes #130  
I've added new packages and restructured classes as suggested in #130.

### CODE REVIEW

**Comment by olenagerasimova** [comment]
@g4s8 please, merge

**Comment by g4s8** [comment]
@olenagerasimova please resolve merge conflicts

**Comment by olenagerasimova** [comment]
@g4s8 done, merge, please

**Comment by 0crat** [comment]
Job `gh:artipie/maven-adapter#134` is not assigned, can't get performer

**Pull request merged**
