### PR TITLE
#222 - support absent content

### LINKED ISSUE #222: Support absent content in proxy
Let's update `asto` and support absent content by returning 404 to the client.

### PR DESCRIPTION
**Pull request by olenagerasimova**
Closes #222 
I've updated asto and corrected `CachedProxySlice` to handle errors by returning 404 to the client.

### CODE REVIEW

**Review by olegmoz — APPROVED** [review]
@olenagerasimova thanks, merging

**Review by olegmoz — CHANGES_REQUESTED** [review]
@olenagerasimova it seems that proxy is broken by these changes. Loks like `MavenProxySliceAuthIT` hangs, please see https://github.com/artipie/maven-adapter/runs/1389537675?check_suite_focus=true

**Comment by olenagerasimova** [comment]
@olegmoz I've disabled failing test and added todo to fix it, all IT pass, I think there is a problem with our matchers, not with proxy slices.

**Review by olegmoz — APPROVED** [review]
@olenagerasimova thanks, merging

**Comment by 0crat** [comment]
Job `gh:artipie/maven-adapter#223` is not assigned, can't get performer

**Pull request merged**
