### PR TITLE
#1: Basic upload

### PR DESCRIPTION
**Pull request by Nimmaster**

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#2](https://github.com/artipie/maven-adapter/issues/2) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/26272380-be68-4f60-a032-0b960703d43e); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/artipie/maven-adapter/issues/2#issuecomment-579300861))

@g4s8 This pull request [#2](https://github.com/artipie/maven-adapter/issues/2) is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/3d96d7da-f74a-4b87-842b-99df9011b8e2); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by g4s8** [comment]
@Nimmaster please add some details to README file, it's not clear now how to start using this module, e.g. where is entry point classes etc

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/artipie/maven-adapter/issues/2#issuecomment-579300861))

@g4s8 There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@542cb6aa2895, thread: PQ-CT2E6TK9B
com.zerocracy.claims.ClaimIn[214] java.lang.IllegalArgumentException: Parameter "age" not found in "Order was canceled" among: [comment, job, issue, repo, cause, _parent_sig, flow, login]
```

[0.51.0](https://github.com/zerocracy/farm): CID: [d3923bd0-76b8-4bc3-b0db-058cce1ea88a](https://www.0crat.com/footprint/CT2E6TK9B/d3923bd0-76b8-4bc3-b0db-058cce1ea88a), Type: "Order was canceled"

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@Nimmaster this PR is too big and hard to review. Can you please split it into few smaller PRs and submit it independently? Also, there are no static analyzers like checkstyle and PMD, we're using qulice maven plugin in other adapters, so it would be great to add it here, it would significantly simplify the review process.

**Comment by 0crat** [comment]
Job was finished in 20 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Pull request [#2](https://github.com/artipie/maven-adapter/issues/2) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by 0crat** [comment]
Order was finished: +20 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Pull request closed without merging**
