### PR TITLE
#69 Extend com.artipie:ppom parent pom

### PR DESCRIPTION
**Pull request by carlosmiranda**
#69 Extended `com.artipie:ppom` parent pom. Fixed some subsequent resulting build errors.

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#76](https://github.com/artipie/maven-adapter/issues/76) is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/f1cbafcc-32ad-467f-a982-b0a903df15f5); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by victornoel** [comment]
> @carlosmiranda after updating we can remove some dependencies from project pom, since they are declared in parent, e.g. junit api and engine, hamcrest libraries, etc

@carlosmiranda yes, in particular please remove the extra slf4j implementations that are already managed by the parent, cf https://github.com/artipie/maven-adapter/issues/69#issuecomment-615887872

**Comment by carlosmiranda** [comment]
@g4s8 done, please see latest commit

**Comment by g4s8** [comment]
@carlosmiranda thanks

**Comment by victornoel** [comment]
@carlosmiranda @g4s8 you forgot to remove logback-classic

**Comment by 0crat** [comment]
Job was finished in 2 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Pull request merged**
