### PR TITLE
#0 - bumped asto and http

### PR DESCRIPTION
**Pull request by olenagerasimova**
Updated asto and http.

### CODE REVIEW

**Comment by genryxy** [comment]
@olenagerasimova let's also update ppom

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Review by g4s8 — DISMISSED** [review]

**Comment by g4s8** [comment]
@olenagerasimova please resolve the conflicat and it'll be merged automatically

**Comment by olenagerasimova** [comment]
@g4s8 thanks, done

**Comment by olenagerasimova** [comment]
@g4s8 could you please approve one more time? Review was dismissed by merge

**Review by g4s8 — APPROVED** [review]

**Pull request merged**
