### PR TITLE
#47: configure logging

### PR DESCRIPTION
**Pull request by Nimmaster**
issue #47

### CODE REVIEW

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#48](https://github.com/artipie/maven-adapter/issues/48), see [§21](http://www.zerocracy.com/policy.html#21); @fanifieiev[/z](https://www.0crat.com/u/fanifieiev) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by Nimmaster** [comment]
@g4s8 should this pull request be considered _trivial_?

**Comment by 0crat** [comment]
Job [#48](https://github.com/artipie/maven-adapter/issues/48) is not in the agenda of @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 12 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: `ARC` didn't merge or close PR, performer @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)[/z](https://www.0crat.com/u/fanifieiev) didn't make CR comments

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Pull request merged**
